stocks:
  AP.UN:
    name: Allied Properties REIT
    url: https://ca.finance.yahoo.com/quote/AP-UN.TO
  AX.UN:
    name: Artis REIT
    url: https://ca.finance.yahoo.com/quote/AX-UN.TO
  BEI.UN:
    name: Boardwalk REIT
    url: https://ca.finance.yahoo.com/quote/BEI-UN.TO
  CAR.UN:
    name: Canadian Apartment Properties REIT
    url: https://ca.finance.yahoo.com/quote/CAR-UN.TO
  CHP.UN:
    name: Choice Properties REIT
    url: https://ca.finance.yahoo.com/quote/CHP-UN.TO
  CRR.UN:
    name: Crombie REIT
    url: https://ca.finance.yahoo.com/quote/CRR-UN.TO
  CRT.UN:
    name: CT REIT
    url: https://ca.finance.yahoo.com/quote/CRT-UN.TO
  DIR.UN:
    name: Dream Industrial REIT
    url: https://ca.finance.yahoo.com/quote/DIR-UN.TO
  D.UN:
    name: Dream Office REIT
    url: https://ca.finance.yahoo.com/quote/D-UN.TO
  FCR.UN:
    name: First Capital REIT
    url: https://ca.finance.yahoo.com/quote/FCR-UN.TO
  GRT.UN:
    name: Granite REIT
    url: https://ca.finance.yahoo.com/quote/GRT-UN.TO
  HR.UN:
    name: H&R REIT
    url: https://ca.finance.yahoo.com/quote/HR-UN.TO
  IIP.UN:
    name: InterRent REIT
    url: https://ca.finance.yahoo.com/quote/IIP-UN.TO
  KMP.UN:
    name: Killam Apartment REIT
    url: https://ca.finance.yahoo.com/quote/KMP-UN.TO
  MI.UN:
    name: Minto Apartment REIT
    url: https://ca.finance.yahoo.com/quote/MI-UN.TO
  MRG.UN:
    name: Morguard North American Residential REIT
    url: https://ca.finance.yahoo.com/quote/MRG-UN.TO
  MRT.UN:
    name: Morguard REIT
    url: https://ca.finance.yahoo.com/quote/MRT-UN.TO
  NWH.UN:
    name: NorthWest Healthcare Properties REIT
    url: https://ca.finance.yahoo.com/quote/NWH-UN.TO
  PLZ.UN:
    name: Plaza REIT
    url: https://ca.finance.yahoo.com/quote/PLZ-UN.TO
  PMZ.UN:
    name: Primaris REIT
    url: https://ca.finance.yahoo.com/quote/PMZ-UN.TO
  PRV.UN:
    name: Pro REIT
    url: https://ca.finance.yahoo.com/quote/PRV-UN.TO
  REI.UN:
    name: RioCan REIT
    url: https://ca.finance.yahoo.com/quote/REI-UN.TO
  SRU.UN:
    name: SmartCentres REIT
    url: https://ca.finance.yahoo.com/quote/SRU-UN.TO
  SOT.UN:
    name: Slate Office REIT
    url: https://ca.finance.yahoo.com/quote/SOT-UN.TO
  SRR.UN:
    name: Slate Retail REIT
    url: https://ca.finance.yahoo.com/quote/SRR-UN.TO
  SMU.UN:
    name: Summit Industrial Income REIT
    url: https://ca.finance.yahoo.com/quote/SMU-UN.TO
  TGA.UN:
    name: True North Commercial REIT
    url: https://ca.finance.yahoo.com/quote/TGA-UN.TO
  TNT.UN:
    name: True North Apartment REIT
    url: https://ca.finance.yahoo.com/quote/TNT-UN.TO
